### ISSUE TITLE
The /limit command breaks the bot

### ISSUE THREAD

**Issue by MBudkin** [sazonovanton/SirChatalot#5]
The /limit command breaks the bot, the following error occurs in the Python window:
```
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\prest\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\prest\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prest\Downloads\SirChatalot-main2\SirChatalot-main\main.py", line 268, in limit_command
    text = ratelimiter(user_id, check=True)
                       ^^^^^^^
NameError: name 'user_id' is not defined
```
After that, the bot is unstable, may not respond to messages until you restart Python.

**Comment by sazonovanton** [comment]
Sorry, I should have tested bot before pushing. I will fix it in a few hours.

**Comment by MBudkin** [comment]
> Sorry, I should have tested bot before pushing. I will fix it in a few hours.

If you need help with testing and prompt answers - I'm in touch! My telegram: @astariot
I will also post here! Thank you!

**Comment by sazonovanton** [comment]
Please check now. Problem should be fixed.
