### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by MBudkin** [sazonovanton/SirChatalot#7]
Hello!
I am getting an error. Am I doing something wrong?

```
  File "C:\Users\prest\Downloads\SirChatalot-main5\SirChatalot-main\main.py", line 75, in <module>
    print(f"Limits for some ({len(user_rates)}) users are set (0 - unlimited).")
                              ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by sazonovanton** [comment]
I'm sorry that this is happening to you, it was such a stupid mistake, I thought that I have tested every case.  
I have fixed it.

**Comment by MBudkin** [comment]
@sazonovanton 

No need to apologize! I understand that writing code is a complex process and you cannot do without errors :)

The program started, but after the first message to the bot, the following error appears:

```
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\prest\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\prest\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prest\Downloads\SirChatalot-main6\SirChatalot-main\main.py", line 310, in answer
    access = await check_user(update, update.message.text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prest\Downloads\SirChatalot-main6\SirChatalot-main\main.py", line 436, in check_user
    ratecheck = ratelimiter(user.id)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prest\Downloads\SirChatalot-main6\SirChatalot-main\main.py", line 114, in ratelimiter
    if user_id in user_rates:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by sazonovanton** [comment]
I need to have some sleep, sorry again :)

Right now it _should_ work

**Comment by sazonovanton** [comment]
I see that you download files as zip (because of SirChatalot-main). I suggest to use `git`, it would be faster to just `git pull` changes :)

`git clone https://github.com/sazonovanton/SirChatalot`

**Comment by MBudkin** [comment]
> I suggest to use `git`

Thanks for the advice, I'll take your advice!

> I need to have some sleep, sorry again :)

Thanks, dear friend!
Everything is working!
I will test the bot and write back to you!

Pleasant dreams!

**Comment by sazonovanton** [comment]
@MBudkin thank you for testing and giving feedback 🥇
